### ISSUE TITLE
Environment variable assignment fails

### ISSUE THREAD

**Issue by efcaguab** [WorldFishCenter/peskas.timor.data.pipeline#33]
When the workflow is running in the main branch the environment variable `R_CONFIG_ACTIVE` is supposed to take the value "production" to do that we use the *allenevans/set-env* action which retrieves the value from a previous step that checks the branch where the code is running. See below for how this work: 

```yaml
      - name: Set variables
        id: setvars
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "::set-output name=r-config::production"
          else
            echo "::set-output name=r-config::default"
          fi
      - name: Set outputs as environment variables
        uses: allenevans/set-env@v2.0.0
        with:
          R_CONFIG_ACTIVE: ${{ steps.setvars.outputs.r-config }}

```

The problem is that *allenevans/set-env* is failing to set the environment variable and therefore the code runs in development mode even when running from the main branch. The step sends the warning below:

```
Warning: Unexpected input(s) 'R_CONFIG_ACTIVE', valid inputs are ['']
Run allenevans/set-env@v2.0.0
  with:
    R_CONFIG_ACTIVE: production
  env:
    KOBO_TOKEN: ***
    GCP_SA_KEY: ***
    AIRTABLE_KEY: ***
``` 

Follow this link for an example of an action run in which this happens https://github.com/WorldFishCenter/peskas.timor.data.pipeline/actions/runs/854950038

I suspect the solution might be as easy as declaring all environment variables in the step rather than at the top level. Declaring the global environment variables in two different places might not be allowed (although I was unable to find any documentation about this)
